app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/', include("first.urls")),
    path('newyear/', include("newyear.urls")),
    path('todolist/', include("todolist.urls")),
]

app/first/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.index, name="index"),
  path("<str:name>", views.greet, name="greet"),
  path("kia/", views.kia, name="kia"),
]

app/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path("", views.index, name="index"),
]

app/todolist/urls.py
from django.urls import path
from . import views

app_name = "todolist"
urlpatterns = [
  path("", views.index, name="index"),
  path("add", views.add, name="add"),
]

app/first/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, "first/index.html")

def kia(request):
  return HttpResponse("Hello, Kia")

def greet(request, name):
  return render(request, "first/greet.html", {
    "name": name.capitalize() 
  })

app/newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
  now = datetime.datetime.now()
  return render(request, "newyear/index.html", {
    "newyear": now.month == 1 and now.day == 1
  })

app/todolist/views.py
from django.http import HttpResponseRedirect
from django import forms
from django.shortcuts import render
from django.urls import reverse


class NewTaskForm(forms.Form):
  task = forms.CharField(label="New Task")

# Create your views here.
def index(request):
  if "tasks" not in request.session:
    request.session["tasks"] = []
  return render(request, "todolist/index.html", {
    "tasks": request.session["tasks"]
  })

def add(request):
  if request.method == "POST":
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data["task"]
      request.session["tasks"] += [task]
      return HttpResponseRedirect(reverse("todolist:index"))
    else:
      return render(request, "todolist/add.html", {
        "form": form
      })
  return render(request, "todolist/add.html", {
    "form": NewTaskForm()
  })

app/first/templates/first/greet.html
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
  </head>
  <body>
    <h1>Hello, {{ name }}!</h1>
  </body>
</html>

app/first/templates/first/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello!</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>

app/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Is it new year's?</title>
    <link rel="stylesheet" href="{% static 'newyear/style.css'%}">
  </head>
  <body>
    <div>
    {% if newyear %}
      <h1>YES</h1>
    {% else %}
      <h1>NO</h1>
    {% endif %}
    </div>
  </body>
</html>

app/todolist/templates/todolist/add.html
{% extends "todolist/layout.html" %}

{% block body %}
  <h1>Add Tasks</h1>
  <form action="{% url 'todolist:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>
  <a href="{% url 'todolist:index' %}">View the Tasks</a>
{% endblock %}

app/todolist/templates/todolist/index.html
{% extends "todolist/layout.html" %}

{% block body%}
<h1>Tasks</h1>
<ul>
  {% for task in tasks %}
  <li>{{ task }}</li>
  {% empty %}
  No Task for now
  {% endfor %}
</ul>

<a href="{% url 'todolist:add' %}">Add a New Task</a>
{% endblock %}

app/todolist/templates/todolist/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>